import 'product_model.dart';

class global {
  static bool data = false;
  static List<Product> products = [
    Product(
      id: 1,
      name: "Beach Bum.Caps",
      price: 1500,
      image: "images/beach-bum-cap.webp",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 2,
      name: "Coffee Break.Caps",
      price: 1099,
      image: "images/coffee-break-cap.webp",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 3,
      name: "Um Training.Caps",
      price: 1800,
      image: "images/um-training-cap.webp",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 4,
      name: "Trucker Monkey.Caps",
      price: 1199,
      image: "images/trucker-monkey-cap.webp",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 5,
      name: "Carry Ninja.Wallet",
      price: 800,
      image: "images/carry-ninja-wallet4.webp",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 6,
      name: "Wallet1.Wallet",
      price: 650,
      image: "images/wallet1.webp",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 7,
      name: "Wallet2.Wallet",
      price: 700,
      image: "images/wallet2.webp",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 8,
      name: "Wallet3.Wallet",
      price: 900,
      image: "images/wallet3.webp",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 9,
      name: "Wallet4.Wallet",
      price: 1200,
      image: "images/untitled-bag.webp",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 10,
      name: "Drip.Hoodie",
      price: 2000,
      image: "images/drip-is-drip-hoodie.webp",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 11,
      name: "Together Effec.Hoodie",
      price: 1800,
      image: "images/together-effec-hoodie.webp",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 12,
      name: "Ethnic Drip.Hoodie",
      price: 2900,
      image: "images/ethnic-drip-hoodie.webp",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 13,
      name: "Life Back Hoodie",
      price: 1400,
      image: "images/life-back-hoodie.webp",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 14,
      name: "UrbanMonkey.Hoodie",
      price: 2800,
      image: "images/UrbanMonkey-hoodie.webp",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 15,
      name: "Easyeveryday.Eyewear",
      price: 1400,
      image: "images/easyeveryday-eyewear.webp",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 16,
      name: "Frontrunner.Caps",
      price: 1500,
      image: "images/Frontrunner.webp",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 17,
      name: "Godfather-Blue.Eyewear",
      price: 1200,
      image: "images/godfather-blue-eyewear.webp",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 18,
      name: "Godfather.Eyewear",
      price: 1450,
      image: "images/godfather-eyewear.webp",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 19,
      name: "Happy Hippie Pink.Eyewear",
      price: 1500,
      image: "images/happy-hippie-pink-eyewear.webp",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 20,
      name: "Nerd Brown.Eyewear",
      price: 900,
      image: "images/nerd-brown-eyewear.webp",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 21,
      name: "Playboi.Eyewear",
      price: 1400,
      image: "images/playboi-eyewear.webp",
      quantity: 0,
      like: "false",
    ),
  ];
}
